### ISSUE TITLE
Crashes when enabling Hotword detection in Arm8 devices

### ISSUE THREAD

**Issue by Ashish117** [timstableford/P-BrainAndroid#11]
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.android.ashish.friday, PID: 2749
                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.android.ashish.brain-2/base.apk"],nativeLibraryDirectories=[/data/app/com.android.ashish.brain-2/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libsnowboy-detect-android.so"
                      at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at ai.kitt.snowboy.snowboyJNI.<clinit>(snowboyJNI.java:13)
                      at ai.kitt.snowboy.snowboyJNI.new_SnowboyDetect(Native Method)
                      at ai.kitt.snowboy.SnowboyDetect.<init>(SnowboyDetect.java:39)
                      at com.android.ashish.friday.HotwordDetector.<init>(HotwordDetector.java:117)
                      at com.android.ashish.friday.MainActivity.finishSetup(MainActivity.java:194)
                      at com.android.ashish.friday.MainActivity.access$100(MainActivity.java:76)
                      at com.android.ashish.friday.MainActivity$2.onSuccess(MainActivity.java:154)
                      at com.android.ashish.friday.ConnectionManager$3$2.run(ConnectionManager.java:204)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by timstableford** [comment]
Sorry, I missed this. Are you running an x86 device?

**Comment by Ashish117** [comment]
I know snowboy won't work on x86 devices but i was saying about Arm64-v8 devices. I try to build the lib using swig and after adding the .so file it is still the same.

**Comment by timstableford** [comment]
Just to double check, you put libsnowboy-detect-android.so into app/src/main/jniLibs/arm64-v8a? If so you may also need to update the Snowboy .java files

**Comment by Ashish117** [comment]
I have put the file in the correct directory but what doyou mean by update
snowboy.java? It doesn’t contain any code!

**Comment by Ashish117** [comment]
I have added the new generated snowboy files also but still it crashes because of missing so file!

**Comment by timstableford** [comment]
Would you mind attaching your APK to this issue please?
